anime/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.conf.urls.static import static
from django.conf import settings

from catalog.views import api_genres, api_genres_detail

urlpatterns = [
    # path('profile/', include('restapp.urls')),
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
    # path('captcha/', include('captcha.urls')),
    # path 'accounts/.....
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(
        template_name='registration/change_pass.html',
        extra_context={'context': 'контекст'}
    ), name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(
        template_name='registration/password_changed.html'
    ), name='password_change_done'),

    path('accounts/password_reset/', PasswordResetView.as_view(
        template_name='registration/reset_password.html',
        subject_template_name='registration/reset_subject.txt',
        email_template_name='registration/reset_email.txt',
        # TODO: Понять что за success_url и прикрутить его
        # success_url=reverse_lazy('accounts/password_reset/done/'),
    ), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(
        template_name='registration/email_sent.html'
    ), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='registration/confirm_password.html'
    ), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(
        template_name='registration/password_confirmed.html'
    ), name='password_reset_complete'),
    path('social/', include('social_django.urls', namespace=' ')),

    # api_restframework
    path('api/genres/<int:pk>/', api_genres_detail),
    path('api/genres/', api_genres),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page
# from anime.settings import DEBUG
# from django.contrib.staticfiles.views import serve
# from django.views.decorators.cache import never_cache

app_name = 'catalog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:anime_id>/', cache_page(60*60)(detail), name='detail'),
    path('random_title/', random_title, name='random_title'),
    path('genre_search/', Genre_search.as_view(), name='genre_search'),
    path('title_search/', title_search, name='title_search'),
    path('genre_search/<int:genre_id>/', genre_titles, name='genre_titles'),
    path('top/', top, name='top'),
    # path('add/', Anime_t_create_view.as_view(), name='add'),
    path('index2/', index2, name='index2'),
    path('tryindex/', tryindex, name='tryindex'),
    path('tryindex2/', tryindex2, name='tryindex2'),
    # path('<int:anime_id>/', Anime_title_detailView.as_view(), name='detail'),
    path('add/', Anime_t_create, name='add'),
    path('add_img/', add_img, name='add_img'),
    path('upload_xml/', upload_xml, name='upload_xml'),
]
# if DEBUG:
#     urlpatterns.append(path('static/<path:path>', never_cache(serve)))

catalog/forms.py
from django.contrib.auth.models import User
from django.core import validators
from django.forms import ModelForm, Select, forms, DecimalField, ModelChoiceField, CharField, NumberInput, IntegerField, \
    SlugField, ModelMultipleChoiceField, ImageField, widgets, FileField
from .models import Anime_title, Genres, Img, Xml_Files
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class Anime_title_form_for_user(ModelForm):
    class Meta:
        model = Anime_title
        fields = ('name_ru',)
        labels = {'name_ru': 'Имя тайтла'}
        help_texts = {'name_ru': ' - Укажи имя тайтла'}
        # widgets = {'name_ru': Select(attrs={'size': 100, 'color': 'yellow'})}


# несрочное TODO: Сделать красивую форму, а то жанры через CTRL жать - такое себе
class Add_Anime_title(ModelForm):
    name_ru = CharField(label='Имя на русском', max_length=250)
    rating = IntegerField(label='Рейтинг', min_value=1, max_value=10)
    genres = ModelMultipleChoiceField(queryset=Genres.objects.all(),
                                      label='Жанры',
                                      help_text='Укажите жанры через CTRL',
                                      required=False)
    captcha = ReCaptchaField(
        widget=ReCaptchaV2Checkbox(
            attrs={
                'data-theme': 'dark',
                # 'data-size': 'compact',
            }
        )
    )

    class Meta:
        model = Anime_title
        fields = ('name_ru', 'rating', 'genres')


class RegisterUserForm(ModelForm):
    password1 = CharField(label='Пароль')
    password2 = CharField(label='Пароль (повторно)')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password1', 'first_name', 'last_name')


class SearchForm(forms.Form):
    keyword = CharField(max_length=30, label='Искомое слово')
    # genres = ModelChoiceField(queryset=Genres.objects.all(),
    #                           label='Жанры')


class XmlForm(ModelForm):
    # xml = FileField(validators=[validators.FileExtensionValidator(
    #     allowed_extensions=('xml', 'xhtml'))],
    #     error_messages={
    #         'invalid': 'Ошибка сервера',
    #         'invalid_extension': 'Этот формат не поддерживается',
    #         'missing': 'Файл не заружен по какой-то причине',
    #         'invalid_image': 'Файл поврежден',
    #         'empty': 'Загружен пустой файл'
    #     })

    class Meta:
        model = Xml_Files
        fields = ('file',)


class ImgForm(ModelForm):
    img = ImageField(label='Изображение',
                     validators=[validators.FileExtensionValidator(
                         allowed_extensions=('gif', 'jpg', 'png'))],
                     error_messages={
                         'invalid': 'Ошибка сервера',
                         'invalid_extension': 'Этот формат не поддерживается',
                         'missing': 'Файл не заружен по какой-то причине',
                         'invalid_image': 'Файл поврежден',
                         'empty': 'Загружен пустой файл'
                     })
    desc = CharField(label='Описание',
                     widget=widgets.Textarea())

    class Meta:
        model = Img
        fields = '__all__'

catalog/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect, \
    StreamingHttpResponse, FileResponse, JsonResponse
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.views.generic.list import ListView
# from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from catalog.models import Anime_title, Genres, Img
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView
from .forms import Anime_title_form_for_user, SearchForm, Add_Anime_title, ImgForm, XmlForm
from django.urls import reverse_lazy, resolve
from django.views.decorators.http import require_http_methods
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from random import randint

from .serializers import GenresSerializer


class IndexView(generic.ListView):
    template_name = 'catalog/index.html'
    context_object_name = 'latest_anime_title_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Anime_title.objects.order_by('-pub_date')[:10]
    # TODO: это метод должен по идее возвращать в 'current_title' аниме по айди, но как я понял это метод для функции detail
    # def get_context_data(self, *, object_list=None, **kwargs):
    #     print(**kwargs)
    #     context = super().get_context_data(**kwargs)
    #     # context['rubrics'] = Rubric.objects.all()
    #     context['current_title'] = Anime_title.objects.get(pk=self.kwargs['anime_id'])
    #     return context


class Genre_search(ListView):
    template_name = 'catalog/genre_search.html'
    context_object_name = 'genres'

    def get_queryset(self):
        return Anime_title.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genres.objects.all()
        return context


# Переопределение функции в класс, чтобы было круче
@require_http_methods(['GET'])
def detail(request, anime_id):
    # print(request.GET)
    data = get_object_or_404(Anime_title, pk=anime_id)
    return render(request, 'catalog/detail.html', {'data': data})


# TODO: у меня нихуя не получается , я тупой нахуй как пробка
# #
# class Anime_title_detailView(SingleObjectMixin, ListView):
#     template_name = 'catalog/index.html'
#     pk_url_kwarg = 'anime_id'
#     def get(self, request, *args, **kwargs):
#         self.object = self.get_object(queryset=Anime_title.objects.all())
#         return super().get(request, *args, **kwargs)
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['current_title'] = self.object
#         context['data'] = context['object_list']
#         return context
#     def get_queryset(self):
#           return Anime_title.objects.all()
def genre_titles(request, genre_id):
    data = Anime_title.objects.filter(genre=genre_id)
    return render(request, 'catalog/genre_titles.html', {'data': data})


@login_required
def top(request, ):
    data = Anime_title.objects.order_by('-rating')[:100]
    return render(request, 'catalog/top.html', {'data': data})


def index2(request):
    response = HttpResponse('Здвесь будет',
                            content_type='text/plain; charset=utf-8')
    response.write(' главная')
    response.writelines((' страница', ' сайта'))
    # response['keywords'] = 'Python, Django'
    response.write(' Python Django')
    return response


def tryindex(request):
    filename = r'E:\photo\pPKmQED_mb8.jpg'
    return FileResponse(open(filename, 'rb'))  # as_attachment=True чтоб сохранить файл)


def tryindex2(request):
    data = {'foo': 'bar'}
    return JsonResponse(data)


def random_title(request):
    data = Anime_title.objects.all()
    title = randint(0, len(data))
    context = Anime_title.objects.get(pk=title)
    return redirect('/catalog/' + str(title), {'data': context})


# Todo: Добавить корректные декораторы к этой функции, изменить форму, а то она некрасивая) и по возможности через bootstrap. Пофиксиить формы, есть форма Anime_title_form_for_user, а есть Add_Anime_title (понять какая лучше и чо зачем и почему)
class Anime_t_create_view(CreateView):
    template_name = 'catalog/create.html'
    form_class = Anime_title_form_for_user
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Anime_title'] = Anime_title.objects.all()
        return context


# TODO: Аналог нормальной формы, нужно потесить
def Anime_t_create(request):
    if request.method == 'POST':
        anime_form = Add_Anime_title(request.POST)
        if anime_form.is_valid():
            anime_form.save()
            return HttpResponseRedirect(reverse('catalog:index'))
        else:
            context = {'form': anime_form}
            return render(request, 'catalog/create.html', context)
    else:
        anime_form = Add_Anime_title()
        context = {'form': anime_form}
        return render(request, 'catalog/create.html', context)


def title_search(request):
    if request.method == 'POST':
        sf = SearchForm(request.POST)
        if sf.is_valid():
            keyword = sf.cleaned_data['keyword'].capitalize()
            # genre_id = sf.cleaned_data['genre'].pk
            anime_titles = Anime_title.objects.filter(name_ru__icontains=keyword, )
            # genre=genre_id)
            data = {'data': anime_titles}
            return render(request, 'catalog/search_results.html', data)
    else:
        sf = SearchForm()
        context = {'form': sf}
        return render(request, 'catalog/search.html', context)


def add_img(request):
    if request.method == 'POST':
        form = ImgForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('catalog:index')
        else:
            context = {'form': form}
            return render(request, 'catalog/add_img.html', context)
    else:
        form = ImgForm()
        context = {'form': form}
        return render(request, 'catalog/add_img.html', context)
def upload_xml(request):
    if request.method == 'POST':
        form = XmlForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('catalog:index')
        else:
            context = {'form': form}
            return render(request, 'catalog/upload_xml.html', context)
    else:
        form = XmlForm()
        context = {'form': form}
        return render(request, 'catalog/upload_xml.html', context)

# api_restwramework

@api_view(['GET', 'POST'])
def api_genres(request):
    if request.method == 'GET':
        genres = Genres.objects.all()
        serializer = GenresSerializer(genres, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = GenresSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,
                            status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'PATCH', 'DELETE'])
def api_genres_detail(request, pk):
    genre = Genres.objects.get(pk=pk)
    if request.method == 'GET':
        serializer = GenresSerializer(genre)
        return Response(serializer.data)
    elif request.method == 'PUT' or request.method == 'PATCH':
        serializer = GenresSerializer(genre, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        genre.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

catalog/templates/catalog/add_img.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Добавь картиночку :)</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Загрузить">
    </form>
<!--    {% for img in imgs %}-->
<!--        <div><img src="{{ img.img.url }}"></div>-->
<!--&lt;!&ndash;        <div><a href="{{ img.img.url }}">Заргрузить картинку</a></div>&ndash;&gt;-->
<!--    {% endfor %}-->
</body>
</html>

catalog/templates/catalog/create.html
<!--{% load bootstrap4 %}-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create FORM</title>
</head>
<body>
    <h1>Предложи аниме для добавления!</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Предложить">
<!--        {% bootstrap_form form %}-->
<!--        {% buttons submit='Предложить'  button_class='btn-primary' %} {% endbuttons %}-->
    </form>
</body>
</html>

catalog/templates/catalog/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css"
    href="{% static 'catalog/style.css' %}">
</head>
<body>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход, <b style="color: red">{{user.username}}</b></p>
    {% else %}
        <p>Выполните вход, так будет больше контента для вас :)</p>
    {% endif %}

    {% if data %}
        <h2>
            {% if data.name_ru %}
                {{ data.name_ru }}
            {% else %}
                Названия на русском нет
            {% endif %}

            {% if data.name_eng %}
                /{{ data.name_eng }}
            {% endif %}

            {% if data.rating %}
                <i>{{ data.rating }}</i>
            {% else %}
                <i>Оценка не выставлена!</i>
            {% endif %}
        </h2>

        {% if data.release_date %}
            <p>Дата релиза: {{ data.release_date }}</p>
        {% else %}
            <p>Даты релиза нет</p>
        {% endif %}

        {% if data.status %}
            <p>Статус: <b>{{ data.status }}</b></p>
        {% else %}
            <p>Статус не выставлен</p>
        {% endif %}

        <p>Жанры:
         {% if data.genre.all %}
            {% for genre in data.genre.all %}
            {{ genre }}
            {% endfor %}
         {% else %}
             не выставлены(
         {% endif %}
        </p>

        {% if data.num_of_episodes %}
            <p>Кол-во эпизодов: {{ data.num_of_episodes }}</p>
        {% else %}
            <p>Кол-во эпизодов не выставлено</p>
        {% endif %}
        {% if data.pub_date %}
            <p>Дата добавления на сайт: {{ data.pub_date }}</p>
        {% endif %}

    {% else %}
        <p>Title does not exists</p>
    {% endif %}
{{ current_title }}
</body>
</html>

catalog/templates/catalog/genre_search.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Все доступные на данный момент жанры</h1>
    {% if genres %}
        {% for genre in genres %}
            <a href="{{ genre.get_absolute_url }}">{{ genre }}</a><br>

        {% endfor %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</body>
</html>

catalog/templates/catalog/genre_titles.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if data %}
        {% for title in data %}
            <p><a href="{{ title.get_absolute_url }}">{{ title.name_ru }} / {{ title.name_eng }}</a></p>
        {% endfor %}
    {% else %}
    <h2>No titles available</h2>
    {% endif %}
</body>
</html>

catalog/templates/catalog/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if user.is_authenticated %}
      Hi {{ user.username }}! <a href="{% url 'logout' %}">Log Out</a> <a href="{% url 'password_change' %}">password_change</a>
    {% else %}
      <p>You are not logged in <a href="{% url 'login' %}">Log In</a></p>
    {% endif %}
    <p>--------------------------</p>
    <p><a href="{% url 'catalog:add' %}">Добавить</a></p>
    <p><a href="{% url 'catalog:random_title' %}">Рандом</a></p>
    <p><a href="{% url 'catalog:genre_search' %}">Поиск по жанрам</a></p>
    <p><a href="{% url 'catalog:title_search' %}">Поиск по названию</a></p>
    {% if latest_anime_title_list %}
    <ul>
    {% for name in latest_anime_title_list %}
<!--        <li><a href="/catalog/{{ name.id }}/">{{ name.name_ru }}</a></li>-->
<!--        <li><a href="{% url 'catalog:detail' name.id %}">{{ name.name_ru }}</a></li>-->
        <li><a href="{{ name.get_absolute_url }}">{{ name.name_ru }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

catalog/templates/catalog/search.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Поиск по названию тайтла</h2>
    {% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Найти">
    </form>
    {% else %}
    <h2>Войдите, чтобы пользоваться поиском</h2>
    {% endif %}
</body>
</html>

catalog/templates/catalog/search_results.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if data %}
        <h2>Все, что удалось найти:</h2>
        {% for anime in data %}
            <p><a href="{{ anime.get_absolute_url }}">{{ anime.name_ru }}</a></p><br>
        {% endfor %}
    {% else %}
        <p>Ничего не удалось найти</p>
    {% endif %}
</body>
</html>

catalog/templates/catalog/top.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>TOP 100</title>
</head>
<p>
    {% if data %}
        {% for title in data %}
            </p><a href="{% url 'catalog:detail' title.id %}">{{ title.name_ru }} - {{ title.rating }}</a></p>
        {% endfor %}
    {% else %}
    <p>No titles are available.</p>
    {% endif %}
</body>
</html>

catalog/templates/catalog/upload_xml.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Upload XML</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Загрузить">
    </form>
<!--    {% for img in imgs %}-->
<!--        <div><img src="{{ img.img.url }}"></div>-->
<!--&lt;!&ndash;        <div><a href="{{ img.img.url }}">Заргрузить картинку</a></div>&ndash;&gt;-->
<!--    {% endfor %}-->
</body>
</html>